global:
  scrape_interval: 15s

scrape_configs:
  - job_name: otel-collector-self
    static_configs:
      - targets: ["otel-collector:8888"]
  - job_name: otel-collector
    static_configs:
      - targets: ["otel-collector:8889"]
