[package]
name = "trading-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "2"
prost = "0.13"
prost-types = "0.13"

[dev-dependencies]
pretty_assertions = "1"
