apiVersion: v1
kind: ServiceAccount
metadata:
  name: trading-core
  namespace: core
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: edge-gateway
  namespace: edge
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ledger-service
  namespace: ledger
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink-jobs
  namespace: streaming
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
  namespace: infra
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: infra
